I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 222, in script
    $ end += 1
  File "game/script.rpy", line 222, in <module>
    $ end += 1
NameError: name 'end' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 222, in script
    $ end += 1
  File "D:\проект по инмформатике\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\проект по инмформатике\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 222, in <module>
    $ end += 1
NameError: name 'end' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Abdul's Code 0.1.7
Sat Mar  9 13:07:29 2024
